### ISSUE TITLE
Rows are smushed together

### ISSUE THREAD

**Issue by anna-pokhilenko** [anna-pokhilenko/flexible-info-card#1]
@hellachella

Hello again :)

Just have a quick question about the rows. I feel like I am probably missing a little thing there, but I can't figure out why the rows aren't stretched across the whole screen.

And my markbot sees the web differently than I do.

**Comment by anna-pokhilenko** [comment]
<img width="1670" alt="Screen Shot 2020-09-09 at 11 01 48 AM" src="https://user-images.githubusercontent.com/55008926/92616142-e388f100-f28b-11ea-9f8f-192254405d3f.png">

Just an example of how I see web and how markbot does. 

@hellachella

**Comment by hellachella** [comment]
Try some different values with your justify-content property. Currently you have it set to flex-start which is the default and will left align everything.

**Comment by anna-pokhilenko** [comment]
@hellachella

Thank you for the help! 

I could make my web work, but I have a couple of problems with Markbot.

So, that is how my web looks like without 
_*, *::before, *::after {
  box-sizing: border-box;
}_
<img width="1680" alt="Screen Shot 2020-09-13 at 9 49 15 PM" src="https://user-images.githubusercontent.com/55008926/93035827-1cb6bd80-f60c-11ea-8f3e-e617d039cdea.png">

And that is how it looks with
<img width="1680" alt="Screen Shot 2020-09-13 at 9 58 28 PM" src="https://user-images.githubusercontent.com/55008926/93036045-b5e5d400-f60c-11ea-9b9f-c69910fc79fb.png">

The thing is that without _*, *::before, *::after {
  box-sizing: border-box;
}_ Markbot will not let me pass. 

It also does not match my web and a screenshot. It sees my web differently than it is online. It says that I have 80% difference.
<img width="797" alt="Screen Shot 2020-09-13 at 10 07 31 PM" src="https://user-images.githubusercontent.com/55008926/93036315-8f746880-f60d-11ea-82f4-0387bff121cc.png">

**Comment by hellachella** [comment]
1. You need to use 
```
*,
*::before,
*::after {
  box-sizing: inherit;
}
```

2. Remove the display flex from the `ul`, (and keep it on the `li)`. remove `flex-direction` and keep `justify-content: center;`.
```
section ul {
  display: flex;  
  flex-direction: column;
  justify-content: center;
  align-items: stretch;
}
```

3. in this part, remove `flex-direction: row;` and a use a different vaue for `justify-content`, also `use align-items`.
```
li {
  display: flex;
  flex-direction: row;
  margin: 1.5rem;
  justify-content: center;
}
```

**Comment by anna-pokhilenko** [comment]
@hellachella 
Thank you! It was still smushed and not as on the screenshot, but I could submit it via markbot)

**Comment by hellachella** [comment]
If this issue is resolved, please close it.
